// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVexbMBilvSF4yD5Pxksan6NKlrkVN_JE',
    appId: '1:657360886987:web:9b43b1038a2b494073cf4e',
    messagingSenderId: '657360886987',
    projectId: 'upuzzle-cfdee',
    authDomain: 'upuzzle-cfdee.firebaseapp.com',
    storageBucket: 'upuzzle-cfdee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvzno-2nSLpLdYMGQqrwMwYlN_6s_vtks',
    appId: '1:657360886987:android:2d8632aee0d33b8673cf4e',
    messagingSenderId: '657360886987',
    projectId: 'upuzzle-cfdee',
    storageBucket: 'upuzzle-cfdee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM9yKmpvdRaSDeOmr2v1w8XHaiO38zcoM',
    appId: '1:657360886987:ios:3f12353602ae0f3a73cf4e',
    messagingSenderId: '657360886987',
    projectId: 'upuzzle-cfdee',
    storageBucket: 'upuzzle-cfdee.appspot.com',
    iosClientId: '657360886987-7khp1abk7sdtrfbpeg87b0094a4lfpgb.apps.googleusercontent.com',
    iosBundleId: 'com.vnappmob.upuzzle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM9yKmpvdRaSDeOmr2v1w8XHaiO38zcoM',
    appId: '1:657360886987:ios:3f12353602ae0f3a73cf4e',
    messagingSenderId: '657360886987',
    projectId: 'upuzzle-cfdee',
    storageBucket: 'upuzzle-cfdee.appspot.com',
    iosClientId: '657360886987-7khp1abk7sdtrfbpeg87b0094a4lfpgb.apps.googleusercontent.com',
    iosBundleId: 'com.vnappmob.upuzzle',
  );
}
