name: Deploy to Firebase Hosting on new release
on:
  release:
    types: [created]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v1.5.0
        with:
          channel: master
      - run: flutter doctor -v

      # Checkout source code and get packages.
      - name: Checkout source code
        uses: actions/checkout@v2
      - run: flutter pub get

      # Build & Deploy to firebase
      - run: flutter build web --release
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_UPUZZLE_CFDEE }}'
          channelId: live
          projectId: upuzzle-cfdee
